onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/clk_i
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/rst_i
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/i_st_wr_en
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/i_st_wr_addr
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/i_st_wr_data
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/i_st_rd_en
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/i_st_rd_addr
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/o_st_rd_data
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/o_st_rd_vld
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/rst_en_n
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/ec_id
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/sc_id
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/chl_priority
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/unit_id
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/unit_ectrl
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/unit_st
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/m_id
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/m_ectrl
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/m_st
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/m_wk_mod
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/m_saf_st
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/link_m_saf_st
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/bhv_en
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/a_task_id
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/a_task_bhv_id
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/a_en
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/a_bhv_ot
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/a_tsc_result_rpt
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/a_tsc_result_vld
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/a_bhv_id
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/a_bhv_vld
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/b_en
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/b_bhv_ot
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/b_tsc_result_rpt
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/b_tsc_result_vld
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/c_en
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/c_bhv_ot
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/c_tsc_result_rpt
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/c_tsc_result_vld
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/c_bhv_gap_crl
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param1
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param2
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param3
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param4
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param5
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param6
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param7
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param8
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param9
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param10
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param11
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param12
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param13
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param14
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param15
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param16
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param17
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param18
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param19
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param20
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param21
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param22
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param23
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param24
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param25
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param26
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param27
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param28
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param29
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param30
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/irq_reg1
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/irq_reg2
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/a_st
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/a_alm_num
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/a_tsc_id
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/b_st
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/b_alm_num
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/b_tsc_id
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/b_bhv_id
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/c_st
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/c_alm_num
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/c_tsc_id
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/c_bhv_id
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param51
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param52
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param53
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param54
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param55
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param56
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param57
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param58
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param59
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param60
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param61
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param62
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param63
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param64
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param65
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param66
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param67
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param68
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param69
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/param70
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/rd_en_d1
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/rd_en_d2
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/rd_space_select
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/wr_space_select
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/wr_task_vld
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/rd_addr_d1
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/rd_addr_d2
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/rd_task_addr
add wave -noupdate /aurora_8b10b_0_TB/emmcc_mst_top_u/emcc_mix_top_u/ec_1di_check_u0/ps_rw_pl_reg_inst/wr_task_addr
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 fs} 0}
quietly wave cursor active 0
configure wave -namecolwidth 412
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {999999050 fs} {999999962 fs}
