onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/clk_i
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/rst
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/i_time_1ms_vld
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/i_time_1s_vld
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/ps_reg_clk
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/ps_reg_reset
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/i_st_wr_en
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/i_st_wr_addr
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/i_st_wr_data
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/i_st_rd_en
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/i_st_rd_addr
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/o_st_rd_data
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/o_st_rd_vld
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/di_i
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/do_o
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/o_intr_irq
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/unit_id
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/unit_ectrl
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/unit_st
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/m_id
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/m_ectrl
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/m_st
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/m_wk_mod
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/m_saf_st
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/link_m_saf_st
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/sc_id
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/ec_id
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/rst_en_n
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/a_bhv_id
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/a_bhv_vld
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/a_task_id
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/a_tx_ot
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/a_tx_result_rpt
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/b_tx_ot
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/b_tx_result_rpt
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/b_en
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/c_tx_ot
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/c_gap_crl
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/c_tx_result_rpt
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/c_en
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/ec_cha_st
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/ec_chb_st
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/ec_chc_st
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/a_bhv_typ
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/a_tx_id
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/a_alm_num
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/b_bhv_id
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/b_tx_id
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/b_alm_num
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/c_bhv_id
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/c_tx_id
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/c_alm_num
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/param1
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/param2
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/param3
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/param4
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/param5
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/param6
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/param7
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/param8
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/task_time_cnt
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/a_tx_result_vld
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/b_tx_result_vld
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/c_tx_result_vld
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/a_pre_sta_allow
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/a_post_sta_allow
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/b_pre_sta_allow
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/b_post_sta_allow
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/c_pre_sta_allow
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/c_post_sta_allow
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/irq_a
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/irq_b
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/irq_c
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/irq_a_grant
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/irq_b_grant
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/irq_c_grant
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/irq_busy_o
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/irq_reg1
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/irq_reg2
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/rst_i
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/chl_priority
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/a_task_bhv_id
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/a_en
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/bhv_en
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/a_bhv_id_r
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/di
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/irq_o
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/irq_ack_i
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/ps_rw_pl_reg_u0/i_st_wr_en
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/ps_rw_pl_reg_u0/i_st_wr_addr
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/ps_rw_pl_reg_u0/i_st_wr_data
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/ps_rw_pl_reg_u0/i_st_rd_en
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/ps_rw_pl_reg_u0/i_st_rd_addr
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/ps_rw_pl_reg_u0/o_st_rd_data
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/ps_rw_pl_reg_u0/o_st_rd_vld
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/proactive_beh_3di_2do_u0/a_en
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/proactive_beh_3di_2do_u0/a_bhv_id
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/proactive_beh_3di_2do_u0/di_i
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/proactive_beh_3di_2do_u0/do_o
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/proactive_beh_3di_2do_u0/curr_state_1d
add wave -noupdate /tb_ec_3di_2do/emcc_mst_top_u/emcc_mix_top_u/ec_3di_2do_u0/proactive_beh_3di_2do_u0/next_state
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {28731362404 fs} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {23080662020 fs} {52993580560 fs}
